---
##
# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
##

# configuration file for the simpleschema plugin
opensearch.notebooks:
  general:
    operationTimeoutMs: 60000 # 60 seconds, Minimum 100ms
    defaultItemsQueryCount: 100 # default number of items to query
  polling:
    jobLockDurationSeconds: 300 # 5 Minutes, Minimum 10 seconds
    minPollingDurationSeconds: 300 # 5 Minutes, Minimum 60 seconds
    maxPollingDurationSeconds: 900 # 15 Minutes, Minimum 5 Minutes
    maxLockRetries: 1 # Max number of retries to retry locking
  access:
    adminAccess: "AllSimpleSchemaObjects"
    # adminAccess values:
    ## Standard -> Admin user access follows standard user
    ## AllSimpleSchemaObjects -> Admin user with "all_access" role can see all  objects of all users.
    filterBy: "NoFilter" # Applied when tenant != __user__
    # filterBy values:
    ## NoFilter -> everyone see each other's simple schema objects
    ## User -> simple schema objects are visible to only themselves
    ## Roles -> simple schema objects are visible to users having any one of the role of creator
    ## BackendRoles -> simple schema objects are visible to users having any one of the backend role of creator
    ignoreRoles: ["own_index", "simpleschema_full_access", "simpleschema_read_access"]
