name: Test and Build OpenSearch Simple Schema Backend Plugin

on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java:
          - 11
          - 17

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
    
      - name: Run Backwards Compatibility Tests
        run: |
          cd opensearch-simpleschema
          echo "Running backwards compatibility tests ..."
          ./gradlew bwcTestSuite -Dtests.security.manager=false
      - name: Build with Gradle
        run: |
          cd opensearch-simpleschema
          ./gradlew build
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: opensearch-simpleschema
          directory: opensearch-simpleschema/
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Create Artifact Path
        run: |
          mkdir -p opensearch-simpleschema-builds
          cp -r ./opensearch-simpleschema/build/distributions/*.zip opensearch-simpleschema-builds/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: opensearch-simpleschema
          path: opensearch-simpleschema-builds
